#include "ali_get_region_host.h"
#include <stdio.h>
namespace {
struct ProductInfo {
  const char* product_name_;
  const char* domain_name_;
};
struct RegionInfo {
  const char* region_name_;
  ProductInfo* productions;
};

// generate from endpoints.xml

ProductInfo product_hangzhou[] = {       
  {
      "ROS",
      "ros.aliyuncs.com"
  },
  {
      "Bss",
      "bss.aliyuncs.com"
  },
  {
      "Ecs",
      "ecs-cn-hangzhou.aliyuncs.com"
  },
  {
      "Oms",
      "oms.aliyuncs.com"
  },
  {
      "Rds",
      "rds.aliyuncs.com"
  },
  {
      "Slb",
      "slb-pop.aliyuncs.com"
  },
  {
      "Oss",
      "oss-cn-hangzhou.aliyuncs.com"
  },
  {
      "OssAdmin",
      "oss-admin.aliyuncs.com"
  },
  {
      "Sts",
      "sts.aliyuncs.com"
  },
  {
      "Yundun",
      "yundun-cn-hangzhou.aliyuncs.com"
  },
  {
      "Risk",
      "risk-cn-hangzhou.aliyuncs.com"
  },
  {
      "Drds",
      "drds.aliyuncs.com"
  },
  {
      "M-kvstore",
      "m-kvstore.aliyuncs.com"
  },
  {
      "Ram",
      "ram.aliyuncs.com"
  },
  {
      "Cms",
      "metrics.aliyuncs.com"
  },
  {
      "Crm",
      "crm-cn-hangzhou.aliyuncs.com"
  },
  {
      "Ocs",
      "pop-ocs.aliyuncs.com"
  },
  {
      "Ots",
      "ots-pop.aliyuncs.com"
  },
  {
      "Dqs",
      "dqs.aliyuncs.com"
  },
  {
      "Location",
      "location.aliyuncs.com"
  },
  {
      "Ubsms",
      "ubsms.aliyuncs.com"
  },
  {
      "Drc",
      "drc.aliyuncs.com"
  },
  {
      "Ons",
      "ons.aliyuncs.com"
  },
  {
      "Aas",
      "aas.aliyuncs.com"
  },
  {
      "Ace",
      "ace.cn-hangzhou.aliyuncs.com"
  },
  {
      "Ubsms-inner",
      "ubsms-inner.aliyuncs.com"
  },
  {
      "Dts",
      "dts.aliyuncs.com"
  },
  {
      "R-kvstore",
      "r-kvstore-cn-hangzhou.aliyuncs.com"
  },
  {
      "PTS",
      "pts.aliyuncs.com"
  },
  {
      "Alert",
      "alert.aliyuncs.com"
  },
  {
      "Push",
      "cloudpush.aliyuncs.com"
  },
  {
      "Emr",
      "emr.aliyuncs.com"
  },
  {
      "Cdn",
      "cdn.aliyuncs.com"
  },
  {
    NULL,
    NULL
  }
};

ProductInfo product_shenzhen[] = 
{
    {
        "ROS",
        "ros.aliyuncs.com"
    },
    {
        "BatchCompute",
        "batchcompute.cn-shenzhen.aliyuncs.com"
    },
   {
        "Bss",
        "bss.aliyuncs.com"
    },
   {
    "Alert",
    "alert.aliyuncs.com"
   },
   {
        "Ecs",
        "ecs-cn-hangzhou.aliyuncs.com"
    },
    {
        "Oms",
        "oms.aliyuncs.com"
    },
    {
        "Rds",
        "rds.aliyuncs.com"
    },
    {
        "Slb",
        "slb-pop.aliyuncs.com"
    },
    {
        "Oss",
        "oss-cn-hangzhou.aliyuncs.com"
    },
    {
        "OssAdmin",
        "oss-admin.aliyuncs.com"
    },
    {
        "Sts",
        "sts.aliyuncs.com"
    },
    {
        "Yundun",
        "yundun-cn-hangzhou.aliyuncs.com"
    },
    {
        "Risk",
        "risk-cn-hangzhou.aliyuncs.com"
    },
    {
        "Drds",
        "drds.aliyuncs.com"
    },
    {
        "M-kvstore",
        "m-kvstore.aliyuncs.com"
    },
    {
        "Ram",
        "ram.aliyuncs.com"
    },
    {
        "Cms",
        "metrics.aliyuncs.com"
    },
    {
        "Crm",
        "crm-cn-hangzhou.aliyuncs.com"
    },
    {
        "Ocs",
        "pop-ocs.aliyuncs.com"
    },
    {
        "Ots",
        "ots-pop.aliyuncs.com"
    },
    {
        "Dqs",
        "dqs.aliyuncs.com"
    },
    {
        "Location",
        "location.aliyuncs.com"
    },
    {
        "Ubsms",
        "ubsms.aliyuncs.com"
    },
    {
        "Drc",
        "drc.aliyuncs.com"
    },
    {
        "Ons",
        "ons.aliyuncs.com"
    },
    {
        "Aas",
        "aas.aliyuncs.com"
    },
    {
        "Ace",
        "ace.cn-hangzhou.aliyuncs.com"
    },
    {
        "Ubsms-inner",
        "ubsms-inner.aliyuncs.com"
    },
    {
        "Dts",
        "dts.aliyuncs.com"
    },
    {
        "R-kvstore",
        "r-kvstore-cn-hangzhou.aliyuncs.com"
    },
    {
        "PTS",
        "pts.aliyuncs.com"
    },
    {
        "Alert",
        "alert.aliyuncs.com"
    },
    {
        "Push",
        "cloudpush.aliyuncs.com"
    },
    {
        "Emr",
        "emr.aliyuncs.com"
    },
    {
        "Cdn",
        "cdn.aliyuncs.com"
    },
    {
      NULL,
      NULL
    }
};

ProductInfo product_qingdao[] = {
  {
      "ROS",
      "ros.aliyuncs.com"
  },
  {
      "BatchCompute",
      "batchcompute.cn-qingdao.aliyuncs.com"
  },
  {
      "Bss",
      "bss.aliyuncs.com"
  },
  {
      "Ecs",
      "ecs-cn-hangzhou.aliyuncs.com"
  },
  {
      "Oms",
      "oms.aliyuncs.com"
  },
  {
      "Rds",
      "rds.aliyuncs.com"
  },
  {
      "Slb",
      "slb-pop.aliyuncs.com"
  },
  {
      "Oss",
      "oss-cn-hangzhou.aliyuncs.com"
  },
  {
      "OssAdmin",
      "oss-admin.aliyuncs.com"
  },
  {
      "Sts",
      "sts.aliyuncs.com"
  },
  {
      "Yundun",
      "yundun-cn-hangzhou.aliyuncs.com"
  },
  {
      "Risk",
      "risk-cn-hangzhou.aliyuncs.com"
  },
  {
      "Drds",
      "drds.aliyuncs.com"
  },
  {
      "M-kvstore",
      "m-kvstore.aliyuncs.com"
  },
  {
      "Ram",
      "ram.aliyuncs.com"
  },
  {
      "Cms",
      "metrics.aliyuncs.com"
  },
  {
      "Crm",
      "crm-cn-hangzhou.aliyuncs.com"
  },
  {
      "Ocs",
      "pop-ocs.aliyuncs.com"
  },
  {
      "Ots",
      "ots-pop.aliyuncs.com"
  },
  {
      "Dqs",
      "dqs.aliyuncs.com"
  },
  {
      "Location",
      "location.aliyuncs.com"
  },
  {
      "Ubsms",
      "ubsms.aliyuncs.com"
  },
  {
      "Drc",
      "drc.aliyuncs.com"
  },
  {
      "Ons",
      "ons.aliyuncs.com"
  },
  {
      "Aas",
      "aas.aliyuncs.com"
  },
  {
      "Ace",
      "ace.cn-hangzhou.aliyuncs.com"
  },
  {
      "Ubsms-inner",
      "ubsms-inner.aliyuncs.com"
  },
  {
      "Dts",
      "dts.aliyuncs.com"
  },
  {
      "R-kvstore",
      "r-kvstore-cn-hangzhou.aliyuncs.com"
  },
  {
      "PTS",
      "pts.aliyuncs.com"
  },
  {
      "Alert",
      "alert.aliyuncs.com"
  },
  {
      "Push",
      "cloudpush.aliyuncs.com"
  },
  {
      "Emr",
      "emr.aliyuncs.com"
  },
  {
      "Cdn",
      "cdn.aliyuncs.com"
  },
  {
    NULL,
    NULL
  }
};
RegionInfo regions[] = {
  {
    "cn-hangzhou",
    product_hangzhou
  },
  {
    "cn-shenzhen",
    product_shenzhen
  },
  {
    "cn-qingdao",
    product_qingdao
  },
  {
    NULL,
    NULL
  }
};

} // end namespace
namespace aliyun {
std::string AliGetEndpointHost(std::string region, std::string product) {
  std::string ret;
  for(int i = 0; regions[i].region_name_ ; i++) {
    for(int j = 0; regions[i].productions[j].product_name_ ; j++) {
      if(regions[i].productions[j].product_name_ == product) {
        ret = regions[i].productions[j].domain_name_;
      }
    }
  }
  return ret;
}
}// end namespace
